# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            /io_forge
tagline:          some_notes_about_programming
description:      some notes about programming
url:              https://github.com/johnnyxavier
baseurl:
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

authorName:           Johnny Xavier
authorAbout:          /pages/about.html

paginate:         4
# paginate_path:    '/page:num'
# Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1
license:            /pages/license.html
about:              /pages/about.html

github:
  repo:             https://github.com/johnnyxavier

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
- title: 'Programming'
  url: '/programming'
- title: 'Java'
  url: '/java'
- title: 'Scala'
  url: '/scala'
- title: 'C'
  url: '/c'
- title: 'Linux'
  url: '#'
  submenu:
  - title: 'Code Highlighter'
    url: '/intro/code-highlighting-post/'
  - title: 'Sample Post'
    url: '/intro/sample-post/'