# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            /io_forge
tagline:          some_notes_about_programming
description:      some notes about programming
url:              https://johnnyxavier.github.io
baseurl:
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

authorName:       Johnny Xavier
authorAbout:      pages/about.html
comments:         true
googleAnalytics:  UA-130252004-1

paginate:         10
# paginate_path:    '/page:num'
# Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.1.0
license:            /pages/license.html
about:              /pages/about.html

github:
  repo:             https://github.com/johnnyxavier